config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :purchases do
    end
  end
  # get 'products/index'
  devise_for :users
  # root to: 'pages#home'
  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'purchases/pay_request'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :purchases
end

app/models/purchase.rb
require 'socket'

class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :product

  def pay_request

    uri = URI.parse("https://stag.wallet.tpaga.co/merchants/api/v1/payment_requests/create")
    request = Net::HTTP::Post.new(uri)
    request.content_type = "application/json"
    request["Authorization"] = "Basic bWluaWFwcC1nYXRvMzptaW5pYXBwbWEtMTIz"
    request["Cache-Control"] = "no-cache"
    request.body = JSON.dump({
      "cost" => cost,
      "purchase_details_url" => return_url,
      "voucher_url" => return_url,
      "idempotency_token" => idempotency_token,
      "order_id" => order_id,
      "terminal_id" => "sede_teusaquillo",
      "purchase_description" => "Compra en Tienda WIlliamTPAGA",
      "user_ip_address" => ip,
      "expires_at" => time
    })

    req_options = {
      use_ssl: uri.scheme == "https",
    }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end

    req_options = {
      use_ssl: uri.scheme == "https",
    }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end

    data = JSON.parse(response.read_body)
    url = data["tpaga_payment_url"]
    # self.body = data["data"]["token"]
    self.update(body: data["data"]["token"])
    data
  end

  def time
    time = Time.now + (60 * 60 * 24)
    return time2 = time.iso8601
  end

  def return_url
    product = self.product.id
    purchase = self.id
    host = ENV["HOST"]

    url = "#{host}/products/#{product}/purchases/#{purchase}"
  end

  def order_id
    purchase = self.id
    400000 + purchase
  end

  def idempotency_token
    purchase = self.id
    80000000000 + purchase * 1234
  end

  def ip
    Socket::getaddrinfo(Socket.gethostname,"echo",Socket::AF_INET)[0][3]
  end

  def url_tpaga
    data = pay_request
    data["data"]["tpaga_payment_url"]
  end

  def cost
    self.product.price * self.quantity
  end

  def status
    body = self.body
    uri = URI.parse("https://stag.wallet.tpaga.co/merchants/api/v1/payment_requests/#{body}/info")
    request = Net::HTTP::Get.new(uri)
    request.content_type = "application/json"
    request["Authorization"] = "Basic bWluaWFwcC1nYXRvMzptaW5pYXBwbWEtMTIz"
    request["Cache-Control"] = "no-cache"

    req_options = {
      use_ssl: uri.scheme == "https",
    }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end

    data = JSON.parse(response.read_body)
    status = data["status"]

  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :purchases
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home

  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only:[:show]

  def index
    @products = Product.all
  end

  def show
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

end

app/controllers/purchases_controller.rb
require 'net/http'
require 'net/https'
require 'uri'
require 'json'

class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @product = Product.find(params[:product_id])
    @purchases = Purchase.all

  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @product = Product.find(params[:product_id])
  end

  # GET /purchases/new
  def new
    @product = Product.find(params[:product_id])
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
    @product = Product.find(params[:product_id])
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @product = Product.find(params[:product_id])
    @purchase = Purchase.new(purchase_params)

    @purchase.quantity = @purchase.quantity
    @purchase.user = current_user
    @purchase.product = @product




    respond_to do |format|
      if @purchase.save
        format.html { redirect_to product_purchase_path(@product, @purchase), notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:quantity)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<% @products.each do |product| %>
  <%= link_to product_path(product) do %>
  <h3><%= product.name %></h3>
  <%end%>
<% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to "Realizar Compra", new_product_purchase_path(@product), class: "btn btn-xs btn-green"  %>


<%= link_to 'Edit', edit_product_purchase_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/purchases/_form.html.erb
<%= simple_form_for [product, purchase] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">


    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchases</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.user %></td>
        <td><%= purchase.product %></td>
        <td><%= purchase.quantity %></td>
        <td><%#= link_to 'Show', purchase %></td>
        <td><%#= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%#= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form', purchase: @purchase, product: @product, button_text: "Enviar solicitud de compra"%>

<%# link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= current_user.email %>
</p>

<p>
  <strong>Product:</strong>
  <%= @purchase.product.name %>
  <%= @purchase.product.description %>
</p>

  <%= link_to 'Pagar en TPAGA-APP', @purchase.url_tpaga %>
<p>
  <strong>Quantity:</strong>
  <%= @purchase.quantity %>

  <strong>Price:</strong>
  <%= @purchase.cost %>

  <strong>Status:</strong>
  <%= @purchase.status %>
</p>

<%#= link_to 'Pagar', purchases_pay_request_path, method: :post %>

<%#= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%#= link_to 'Back', purchases_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%#= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/wecalderonc", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>